#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Mar 30, 2019 08:51:01 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import testol_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    testol_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    testol_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+466+152")
        top.title("SAST Database manager")
        top.configure(background="#d9d9d9")

        self.Custom1 = testol_support.Custom(top)
        self.Custom1.place(relx=0.45, rely=0.244, relheight=0.167
                , relwidth=0.208)

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.017, rely=0.022, relheight=0.967
                , relwidth=0.975)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")
        self.Frame2.configure(width=585)

        self.Label1 = tk.Label(self.Frame2)
        self.Label1.place(relx=0.034, rely=0.046, height=41, width=141)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Unique ID (Roll No.)''')
        self.Label1.configure(width=141)

        self.Label2 = tk.Label(self.Frame2)
        self.Label2.place(relx=0.137, rely=0.138, height=21, width=78)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Name''')
        self.Label2.configure(width=78)

        self.Label3 = tk.Label(self.Frame2)
        self.Label3.place(relx=0.137, rely=0.207, height=21, width=75)
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Subject''')
        self.Label3.configure(width=75)

        self.Label4 = tk.Label(self.Frame2)
        self.Label4.place(relx=0.12, rely=0.276, height=21, width=87)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Hierarchy''')
        self.Label4.configure(width=87)

        self.Label5 = tk.Label(self.Frame2)
        self.Label5.place(relx=0.051, rely=0.345, height=21, width=118)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Homeroom Class''')
        self.Label5.configure(width=118)

        self.Listbox1 = tk.Listbox(self.Frame2)
        self.Listbox1.place(relx=0.017, rely=0.69, relheight=0.257
                , relwidth=0.947)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(disabledforeground="#a3a3a3")
        self.Listbox1.configure(font="TkFixedFont")
        self.Listbox1.configure(foreground="#000000")
        self.Listbox1.configure(width=554)

        self.Entry1 = tk.Entry(self.Frame2)
        self.Entry1.place(relx=0.256, rely=0.069,height=20, relwidth=0.28)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(width=164)

        self.Entry2 = tk.Entry(self.Frame2)
        self.Entry2.place(relx=0.256, rely=0.138,height=20, relwidth=0.28)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Entry3 = tk.Entry(self.Frame2)
        self.Entry3.place(relx=0.256, rely=0.207,height=20, relwidth=0.28)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")

        self.Entry4 = tk.Entry(self.Frame2)
        self.Entry4.place(relx=0.256, rely=0.276,height=20, relwidth=0.28)
        self.Entry4.configure(background="white")
        self.Entry4.configure(disabledforeground="#a3a3a3")
        self.Entry4.configure(font="TkFixedFont")
        self.Entry4.configure(foreground="#000000")
        self.Entry4.configure(insertbackground="black")

        self.Entry5 = tk.Entry(self.Frame2)
        self.Entry5.place(relx=0.256, rely=0.345,height=20, relwidth=0.28)
        self.Entry5.configure(background="white")
        self.Entry5.configure(disabledforeground="#a3a3a3")
        self.Entry5.configure(font="TkFixedFont")
        self.Entry5.configure(foreground="#000000")
        self.Entry5.configure(insertbackground="black")

        self.TButton1 = ttk.Button(self.Frame2)
        self.TButton1.place(relx=0.017, rely=0.483, height=45, width=156)
        self.TButton1.configure(takefocus="")
        self.TButton1.configure(text='''Add''')
        self.TButton1.configure(width=156)

        self.TButton2 = ttk.Button(self.Frame2)
        self.TButton2.place(relx=0.342, rely=0.483, height=45, width=156)
        self.TButton2.configure(takefocus="")
        self.TButton2.configure(text='''Modify''')
        self.TButton2.configure(width=156)

        self.TButton3 = ttk.Button(self.Frame2)
        self.TButton3.place(relx=0.684, rely=0.483, height=45, width=156)
        self.TButton3.configure(takefocus="")
        self.TButton3.configure(text='''Remove''')
        self.TButton3.configure(width=156)

if __name__ == '__main__':
    vp_start_gui()





